config/routes.rb
Rails.application.routes.draw do

  post 'guests'=> 'guest#new'
  get '/' => 'home#index'
  get 'callback' => 'host#callback'
  get 'new' => 'host#new'
  post 'create' => 'host#create'
  post 'join' => 'host#join'
  post 'like' => 'song#like'
  post 'dislike' => 'song#dislike'
  post 'update' => 'playlist#update'
  get 'logout' => 'host#logout'
  post 'update_playlist' => 'song#update_playlist'

  get 'nuke' => 'host#nuke'

  resources :host, :key => :room, :path => 'party' do
     post 'search' => 'song#search'
     post 'create' => 'song#create'
  end

end

app/models/host.rb
class Host < ActiveRecord::Base

	has_one :playlist
	has_many :guests

	def self.party_setup access_token  
		rdio = Rdio.new([Rails.configuration.rdio[:key], Rails.configuration.rdio[:secret]], 
                    access_token)
	  	playlists = []
			temp = rdio.call('getPlaylists')['result']['owned']
			temp.each_with_index do |v, i|
				playlists << temp[i]
			end
	  	playlists
	end

	def self.get_auth uri
		rdio = Rdio.new([Rails.configuration.rdio[:key], Rails.configuration.rdio[:secret]])
		callback_url = (URI.join uri, '/callback').to_s
		url = rdio.begin_authentication(callback_url)
		rdio.token = url
		rdio
	end

	def self.rdio_init id
		host = Host.find_by_room id
		access_token = host.at
	  	access_token_secret = host.ats
		rdio = Rdio.new([Rails.configuration.rdio[:key], Rails.configuration.rdio[:secret]], 
			access_token)
	end

	def self.party
		party = '/party/' + params[:room]
	end

	def to_param
		"#{room}"
	end
end

app/controllers/host_controller.rb
require 'net/http'
require 'net/https'

class HostController < ApplicationController
	def new
	  	if has_access_token?
	  		@playlists = Host.party_setup access_token
	  		@currentUser = session['user']
		else
			session.clear
			redirect_to 'https://www.rdio.com/oauth2/authorize/?response_type=code&client_id=fcjhwmdw35hxxjlrkcni63gwnq&redirect_uri=http://www.prdio.com/callback'
		end
	end


	def show
		@host = Host.find_by( room: params[:id] )
		if session[:host] == @host.room
			@thehost = true
		elsif session[:guest_id].present?
			@guest = Guest.find_by_id session[:guest_id]
		else
			redirect_to '/'
		end
		rdio = Host.rdio_init params[:id]
	end

	def create
		access_token = session[:at]
	  	# access_token_secret = session[:ats]
		rdio = Rdio.new([Rails.configuration.rdio[:key], Rails.configuration.rdio[:secret]], 
			access_token)
		if new_party['reuse'].blank?
			@playlist = rdio.call('createPlaylist', ({ "name" => new_party['playlist'], "description" => "", "tracks" => "" }))
			@playlist = @playlist['result']['key']
		else
			@playlist = new_party['reuse']
		end
		@host = Host.new(
				key: session['user']['key'], 
				room: (0...4).map { (65 + rand(26)).chr }.join, 
				username: session['user']['firstName'], 
				at: session[:at], 
				ats: session[:ats])
		if @host.save
			session[:host] = @host.room
			Playlist.create(key: @playlist, host_id: @host.id, name: new_party['playlist'] )
			if new_party['reuse'].present?
				rdio.songs_for_playlist(@host.playlist.key).each do |s|
					Song.create(
						title: s['name'], 
		  				artist: s['artist'], 
		  				key: s['key'], 
		  				playlist_id: @host.playlist.id, 
		  				image: s['dynamicIcon'] )
				end
			end
			redirect_to '/party/' + @host.room
		else
			render 'new'
		end

	end


	def callback
		code = params[:code]
		key = ENV["RDIO_CONSUMER_KEY"]
		secret = ENV["RDIO_CONSUMER_SECRET"]
		url = "https://services.rdio.com/oauth2/token"

		uri = URI(url)

		Net::HTTP.start(uri.host, uri.port,
		  :use_ssl => uri.scheme == 'https', 
		  :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |http|

		  request = Net::HTTP::Post.new uri.request_uri
		  request.basic_auth key, secret
		  request.set_form_data({
		  	grant_type: 'authorization_code',
		  	code: code,
		  	redirect_uri: 'http://www.prdio.com/callback'
		  })

		  response = http.request request # Net::HTTPResponse object
		  response = JSON.parse response.body

		  session[:at] = response['access_token']
		  rdio = Rdio.new([
				Rails.configuration.rdio[:key], 
				Rails.configuration.rdio[:secret]], 
			access_token)
		  session[:user] = rdio.call('currentUser')['result']
		end
		redirect_to('/new')
	end

	def logout
  		session.clear
  		redirect_to ('/')
	end

	def new_party
		new_party = params.require(:create).permit(:playlist, :reuse)
	end

	def nuke
		rdio = Host.rdio_init params[:id]
		playlists = []
		temp = rdio.call('getPlaylists')['result']['owned']
		temp.each_with_index do |v, i|
			playlists << temp[i]['key']
		end
		temp.each_with_index do |v ,i|
			rdio.call('deletePlaylist', ({ playlist: playlists[i] }))
		end
		redirect_to ('/')
	end

	def access_token
		session[:at]
	end

	def access_token_secret
		session[:ats]
	end

	def has_access_token?
		access_token
	end

	def join
		redirect_to Host.party
	end
end

app/helpers/host_helper.rb
module HostHelper
	def embedded_svg filename, options={}
	    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
	    doc = Nokogiri::HTML::DocumentFragment.parse file
	    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
  end
end

app/views/host/_playback.html.erb
<div class="playback-container">
  <div id="apiswf"></div>
  <input id="play_key" type="hidden" value="<%= @host.playlist.key %>">
  <input id="highest_key" type="hidden" value="">
  <progress max="100" value="0" id="progress"></progress>
  <div class="artistAlbumInfo">
    <img src="/assets/prdio-logo2.svg" id="art" class="albumArt">
  </div>
  <h3 class='trackInfo'><span id="artist"></span><span class='divider'><br></span><span id="track"></span></h3>
  <div class="controls">
    <span class='resume>'></span>
    <%= embedded_svg 'play.svg', class: "play" %>
    <%= embedded_svg 'stop.svg', class: "stop" %>
    <%= embedded_svg 'pause.svg', class: "pause" %>
    <%= embedded_svg 'next-prev.svg', class: "modular next" %>
  </div>
  <div id='freq'>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
  </div>
</div>

app/views/host/_tracks.html.erb
<ul id='tracks'>
		<% @host.playlist.songs.sort_by {|song| [song.vote]}.reverse.each do |song| %>
			<li class='track<%= song.id %> track'>
				<img src='<%= song.image %>' class='trackIcon'>
				<div class='trackInfo'>
					<%= song.title %><br>
					<%= song.artist %><br>
					Vote: <span class='vote'><%= song.vote %></span>
				<% if @guest.present? %>
				<% if song.in?(@guest.songs) %>
					Voted.
				<% else %>
				</div>
					<div class='like' id='<%= song.id %>'>
						<%= form_tag like_path, { remote: true } do %>
							<%= submit_tag 'Like', { class: 'like_button' } %>
							<%= hidden_field_tag 'song', song.id %>
							<%= hidden_field_tag 'host_id', song.playlist.host.id %>
						<% end %>
						<%= form_tag dislike_path, { remote: true } do %>
							<%= submit_tag 'Dislike', { class: 'dislike_button' } %>
							<%= hidden_field_tag 'song', song.id %>
							<%= hidden_field_tag 'host_id', song.playlist.host.id %>
						<% end %>
					</div>
				<% end %>	
			<% end %>
			</li>
		<% end %>
	</ul>

app/views/host/new.html.erb
<%= javascript_tag do %>
$(function() {
	$('.playlistChoice').click(function() {
		var form = $(this).parents('form:first');
		form.submit();
	});
});
<% end %>
<div class="startInstructions">
	<p> Hello <%= @currentUser["firstName"] %>, enter a playlist name:</p>

	<!-- not sure how to select the form below-->
	<div class="playlistForm">
		<%= form_for :create, url: create_path do |f| %>
			<%= f.text_field :playlist %>
			<%= f.submit "Create!", { class: 'join' } %>
		<% end %>
	</div>

	<p>Or, select one of your existing playlists:</p>
</div>
<div class='playlist_select'>
<% @playlists.each_with_index do |v, i| %>
	<%= form_for :create, url: create_path do |f| %>
		<div class="playlistChoice">
			<%= v['name'] %>
			<%= hidden_field_tag 'create[playlist]', v['name'] %>
			<%= hidden_field_tag 'create[reuse]', v['key'] %>
		</div>
	<% end %>
<% end %>
</div>

app/views/host/show.html.erb
<div class="background"></div>
 <% if flash[:error] %>
    <div class="error"><span class='error_message'><%= flash[:error] %></span><img src='http://media.giphy.com/media/1aBHzBi3jSItG/giphy.gif'></div>
  <% end %>
<div class="songList">
  <div id='turntable'>
  	<%= embedded_svg 'prdio-logo2.svg', class: "plogo" %>
    <div id="circle">
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="175px" height="175px" viewBox="0 0 400 400" enable-background="new 0 0 400 400" xml:space="preserve">
          <defs>
            <path id="circlePath" d=" 
             M 200, 200 
             m -110, 0 
             a 120,120 0 0,1 240,0 
             a 120,120 0 0,1 -240,0">
             </path>
            <path id="circlePath2" d=" M 200, 200 
            m -140, 0 
            a 130,130 0 0,1 300,0 
            a 130,130 0 0,1 -300,0">
            </path>
          </defs>
          <circle cx="150" cy="150" r="50" fill="#000" style='stroke-opacity: 0;fill: none;'/>
          <g>
              <use xlink:href="#circlePath" fill="none"/>
              <text fill="#fff">
                  <textPath xlink:href="#circlePath" style='font-size: 30px;' id='circleText'></textPath>
              </text>
          </g>
          <g>
              <use xlink:href="#circlePath2" fill="none"/>
              <text fill="#fff">
                  <textPath xlink:href="#circlePath2" style='font-size: 30px;' id='circleText2'> ♬ <%= @host.playlist.name %> ♬ </textPath>
              </text>
          </g>
      </svg>
    </div>
    <%= hidden_field_tag 'playlist', @host.playlist.name %>
  </div>
  <% if @guest.present? %>
    <div class="songSearch">
      <%= form_tag @host.room + '/search/' do %>
        <%= text_field_tag :title, '', { placeholder: 'Search for Tracks', id: 'search-data', autocomplete: 'off', autocorrect: 'off' } %> <br />
        <%= submit_tag 'Find Songs', { id: 'search' } %>
      <% end %>
    </div>
  <% end %>
  <span class="code">room code:</span>
  <h2> <span class="roomcode resize"><%= @host.room %></span>
  <span class="name"><%= @host.playlist.name %> </h3></h2>
</div>
<%= hidden_field_tag 'host', @host.id %>
<div id="switcher" data-uri="<%= request.host %>:<%= request.port %>/websocket">
	<ul id='tracks'>
      <% @songs = @host.playlist.songs %>
      <% @songs.sort_by {|song| [song.vote, song.id]}.reverse.each do |song| %>
        <li class="track" data-id="<%= song.id %>" data-key="<%= song.key %>" data-order="0">
          <div class='track-arrow'>
            <img src='<%= song.image %>' class='trackIcon'>
            <div class='trackInfo'>
              <span class='track-title'><%= truncate(song.title, legnth: 15) %></span><br>
              <span class='track-artist'><%= song.artist %></span><br>
              Vote: <span class='vote'><%= song.vote %></span>
            </div>
          </div>
            <% if @guest.present? %>
            <% if song.in?(@guest.songs) %>
            <% else %>
            <div class='like' id='<%= song.id %>'>
              <%= form_tag like_path, { remote: true } do %>
                <%= embedded_svg 'thumbs-up-down.svg', class: "vote_btn like_button" %>
                <%= hidden_field_tag 'song', song.id %>
                <%= hidden_field_tag 'host_id', song.playlist.host.room %>
              <% end %>
              <%= form_tag dislike_path, { remote: true } do %>
                <%= embedded_svg 'thumbs-up-down.svg', class: "vote_btn dislike_button" %>
                <%= hidden_field_tag 'song', song.id %>
                <%= hidden_field_tag 'host_id', song.playlist.host.room %>
              <% end %>
            </div>
          <% end %> 
        <% end %>
        </li>
      <% end %>
    </ul>
</div>
<% if @thehost %>
  <%= hidden_field_tag 'guest', 'HOST' %>
	<%= render "playback" %>
<% end %>